import { object, ObjectSchema } from "yup";
import { Appendix8Input } from "./appendix8Type";
import { validationMessages } from "@/shared/constants";
import { stringField } from "@/shared/utils/functions";

export const appendix8Schema: ObjectSchema<Appendix8Input> = object({
  //Section A
  relateToDailyLife: stringField(validationMessages.required),
  usePriorKnowledge: stringField(validationMessages.required),
  promoteParticipation: stringField(validationMessages.required),
  intentionalDevelopment: stringField(validationMessages.required),
  integratePlay: stringField(validationMessages.required),
  buildSecureSpace: stringField(validationMessages.required),
  spaceAlignmentToGoals: stringField(validationMessages.required),
  organizeZoneCriteria: stringField(validationMessages.required),
  selectAppropriateMaterials: stringField(validationMessages.required),
  renewZoneCapacity: stringField(validationMessages.required),
  promoteFreeZoneRotation: stringField(validationMessages.required),
  holisticDevelopmentFocus: stringField(validationMessages.required),
  facilitatePeerInteraction: stringField(validationMessages.required),
  promoteEmotionalExpression: stringField(validationMessages.required),
  observeListenMediateSupport: stringField(validationMessages.required),
  knowledgeAndUse: stringField(validationMessages.required),
  curriculumAdaptation: stringField(validationMessages.required),
  implementWorkshops: stringField(validationMessages.required),
  implementProjects: stringField(validationMessages.required),
  implementAssembly: stringField(validationMessages.required),
  varyStudentGrouping: stringField(validationMessages.required),
  planTransitions: stringField(validationMessages.required),
  organizeRoutineCriteria: stringField(validationMessages.required),
  useAnticipationTools: stringField(validationMessages.required),
  addressNeedsViaSchedule: stringField(validationMessages.required),
  flexibleRespectfulTiming: stringField(validationMessages.required),
  clearCoherentSchedule: stringField(validationMessages.required),
  integratesDesignElements: stringField(validationMessages.required),
  involveFamilies: stringField(validationMessages.required),
  usesVariedTools: stringField(validationMessages.required),
  documentsObservations: stringField(validationMessages.required),
  flexibleInclusiveDesign: stringField(validationMessages.required),
  individualizedSupportiveAssessment: stringField(validationMessages.required),
  //Section B
  affectiveEnvironment: stringField(validationMessages.required),
  fosterResponsibilityAutonomy: stringField(validationMessages.required),
  cozySafeEnjoyable: stringField(validationMessages.required),
  positiveAttitudeRoutines: stringField(validationMessages.required),
  usePositiveFeedback: stringField(validationMessages.required),
  respectfulAffectionateTreatment: stringField(validationMessages.required),
  listenToInterests: stringField(validationMessages.required),
  addressChildNeeds: stringField(validationMessages.required),
  promoteEmpathyConflict: stringField(validationMessages.required),
  fosterTeamworkCollaboration: stringField(validationMessages.required),
  promoteFreeExpression: stringField(validationMessages.required),
  //Section C
  promoteFamilyParticipation: stringField(validationMessages.required),
  listenToOpinions: stringField(validationMessages.required),
  receptiveToProposals: stringField(validationMessages.required),
  facilitateCollaborationActivities: stringField(validationMessages.required),
  considerFamilyContext: stringField(validationMessages.required),
  communicateProgressMechanisms: stringField(validationMessages.required),
  adherenceToComprehensiveCare: stringField(validationMessages.required),
  //Section D
  setRealisticGoals: stringField(validationMessages.required),
  selfAssessPractice: stringField(validationMessages.required),
  peerEvaluateForImprovement: stringField(validationMessages.required),
  sharePracticeActivities: stringField(validationMessages.required),
  teamConsensusPlanning: stringField(validationMessages.required),
  manageVirtualClassroom: stringField(validationMessages.required),
  useGoogleProductivity: stringField(validationMessages.required),
  useAgeAppropriateResources: stringField(validationMessages.required),
  integrateAudiovisualTools: stringField(validationMessages.required),
});
