import { object, ObjectSchema } from "yup";
import { Appendix8Input } from "./type";
import { validationMessages } from "@/shared/constants";
import { stringField, dateField } from "@/shared/utils/funtions";

export const appendix8Schema: ObjectSchema<Appendix8Input> = object({
  ask1: stringField(validationMessages.required),
  ask2: stringField(validationMessages.required),
  ask3: stringField(validationMessages.required),
  ask4: stringField(validationMessages.required),
  ask5: stringField(validationMessages.required),
  ask6: stringField(validationMessages.required),
  ask7: stringField(validationMessages.required),
  ask8: stringField(validationMessages.required),
  ask9: stringField(validationMessages.required),
  ask10: stringField(validationMessages.required),
  ask11: stringField(validationMessages.required),
  ask12: stringField(validationMessages.required),
  ask13: stringField(validationMessages.required),
  ask14: stringField(validationMessages.required),
  ask15: stringField(validationMessages.required),
  ask16: stringField(validationMessages.required),
  ask17: stringField(validationMessages.required),
  ask18: stringField(validationMessages.required),
  ask19: stringField(validationMessages.required),
  ask20: stringField(validationMessages.required),
  ask21: stringField(validationMessages.required),
  ask22: stringField(validationMessages.required),
  ask23: stringField(validationMessages.required),
  ask24: stringField(validationMessages.required),
  ask25: stringField(validationMessages.required),
  ask26: stringField(validationMessages.required),
  ask27: stringField(validationMessages.required),
  ask28: stringField(validationMessages.required),
  ask29: stringField(validationMessages.required),
  ask30: stringField(validationMessages.required),
  ask31: stringField(validationMessages.required),
  ask32: stringField(validationMessages.required),
  ask33: stringField(validationMessages.required),
  ask34: stringField(validationMessages.required),
  ask35: stringField(validationMessages.required),
  ask36: stringField(validationMessages.required),
  ask37: stringField(validationMessages.required),
  ask38: stringField(validationMessages.required),
  ask39: stringField(validationMessages.required),
  ask40: stringField(validationMessages.required),
  ask41: stringField(validationMessages.required),
  ask42: stringField(validationMessages.required),
  ask43: stringField(validationMessages.required),
  ask44: stringField(validationMessages.required),
  ask45: stringField(validationMessages.required),
  ask46: stringField(validationMessages.required),
  ask47: stringField(validationMessages.required),
  ask48: stringField(validationMessages.required),
  ask49: stringField(validationMessages.required),
  ask50: stringField(validationMessages.required),
  ask51: stringField(validationMessages.required),
  ask52: stringField(validationMessages.required),
  ask53: stringField(validationMessages.required),
  ask54: stringField(validationMessages.required),
  ask55: stringField(validationMessages.required),
  ask56: stringField(validationMessages.required),
  ask57: stringField(validationMessages.required),
  ask58: stringField(validationMessages.required),
  ask59: stringField(validationMessages.required),
});