import { AxiosMessage } from "@/shared/types/globals";

export interface Appendix8Input {
  ask1: string;
  ask2: string;
  ask3: string;
  ask4: string;
  ask5: string;
  ask6: string;
  ask7: string;
  ask8: string;
  ask9: string;
  ask10: string;
  ask11: string;
  ask12: string;
  ask13: string;
  ask14: string;
  ask15: string;
  ask16: string;
  ask17: string;
  ask18: string;
  ask19: string;
  ask20: string;
  ask21: string;
  ask22: string;
  ask23: string;
  ask24: string;
  ask25: string;
  ask26: string;
  ask27: string;
  ask28: string;
  ask29: string;
  ask30: string;
  ask31: string;
  ask32: string;
  ask33: string;
  ask34: string;
  ask35: string;
  ask36: string;
  ask37: string;
  ask38: string;
  ask39: string;
  ask40: string;
  ask41: string;
  ask42: string;
  ask43: string;
  ask44: string;
  ask45: string;
  ask46: string;
  ask47: string;
  ask48: string;
  ask49: string;
  ask50: string;
  ask51: string;
  ask52: string;
  ask53: string;
  ask54: string;
  ask55: string;
  ask56: string;
  ask57: string;
  ask58: string;
  ask59: string;
  questionMap?: any;
}

export type IAppendix8Input = Appendix8Input & AxiosMessage;
