import { object, ObjectSchema } from "yup";
import { Attachment8Input } from "./type";
import { validationMessages } from "@/shared/constants";
import { stringField } from "@/shared/utils/functions";

export const attachment8Schema: ObjectSchema<Attachment8Input> = object({
  startDate: stringField(validationMessages.required),
  connectsDevelopmental: stringField(validationMessages.required),
  revisitsKnowledge: stringField(validationMessages.required),
  promotesParticipation: stringField(validationMessages.required),
  intentionallyControls: stringField(validationMessages.required),
  integratesPlay: stringField(validationMessages.required),
  createsSafeCreative: stringField(validationMessages.required),
  recognizesImportance: stringField(validationMessages.required),
  organizesDevelopment: stringField(validationMessages.required),
  selectSafe: stringField(validationMessages.required),
  enrichesAndReviews: stringField(validationMessages.required),
  includePromotes: stringField(validationMessages.required),
  plansActivities: stringField(validationMessages.required),
  selectAndOrganizes: stringField(validationMessages.required),
  promotesExpression: stringField(validationMessages.required),
  willAssist: stringField(validationMessages.required),
  knowsAndUses: stringField(validationMessages.required),
  adaptsPedagogical: stringField(validationMessages.required),
  revelantPedagogical: stringField(validationMessages.required),
  integratesRelevantPedagogical: stringField(validationMessages.required),
  integratesPedagogicalStrategy: stringField(validationMessages.required),
  usesDifferentTypes: stringField(validationMessages.required),
  takesCaresOf: stringField(validationMessages.required),
  organizesDayRoutines: stringField(validationMessages.required),
  usesTools: stringField(validationMessages.required),
  respondsBasicNeeds: stringField(validationMessages.required),
  takesCriterion: stringField(validationMessages.required),
  organizesDayTime: stringField(validationMessages.required),
  considerKeyElements: stringField(validationMessages.required),
  involvesFamilies: stringField(validationMessages.required),
  usesVarietyTools: stringField(validationMessages.required),
  recordAndDocument: stringField(validationMessages.required),
  plansAccountPrinciple: stringField(validationMessages.required),
  characteristicsAgeGroup: stringField(validationMessages.required),
  affectiveLearningEnvironment: stringField(validationMessages.required),
  offersOportunities: stringField(validationMessages.required),
  welcomingAndSafe: stringField(validationMessages.required),
  displaysPositiveAttitudes: stringField(validationMessages.required),
  positiveLanguageFeedback: stringField(validationMessages.required),
  respectfullyAndLovingly: stringField(validationMessages.required),
  pedagogicalPractices: stringField(validationMessages.required),
  respondsOfNeeds: stringField(validationMessages.required),
  promotesAttitudes: stringField(validationMessages.required),
  teamworkClassroom: stringField(validationMessages.required),
  promotesFreeExpression: stringField(validationMessages.required),
  promotesFamilyParticipation: stringField(validationMessages.required),
  listenAndRespect: stringField(validationMessages.required),
  showReceptiveAttitude: stringField(validationMessages.required),
  familiesSomeActivity: stringField(validationMessages.required),
  accountFamilyContext: stringField(validationMessages.required),
  communicationMechanism: stringField(validationMessages.required),
  comprehensiveModel: stringField(validationMessages.required),
  setsGoals: stringField(validationMessages.required),
  selfEvaluates: stringField(validationMessages.required),
  seekContinuousImprovment: stringField(validationMessages.required),
  activitiesWorkshop: stringField(validationMessages.required),
  agreementOfPlanning: stringField(validationMessages.required),
  manageVirtualClassroom: stringField(validationMessages.required),
  googleDriveDocs: stringField(validationMessages.required),
  technologicalResources: stringField(validationMessages.required),
  usesAudiovisualEquipment: stringField(validationMessages.required)
});
