import { AxiosMessage } from "@/shared/types/globals";

export interface Attachment7Input {
  connectsDevelopmental: string;
  revisitsKnowledge: string;
  promotesParticipation: string;
  intentionallyControls: string;
  integratesPlay: string;
  createsSafeCreative: string;
  recognizesImportance: string;
  organizesDevelopment: string;
  selectSafe: string;
  enrichesAndReviews: string;
  includePromotes: string;
  plansActivities: string;
  selectAndOrganizes: string;
  promotesExpression: string;
  willAssist: string;
  knowsAndUses: string;
  adaptsPedagogical: string;
  revelantPedagogical: string;
  integratesRelevantPedagogical: string;
  integratesPedagogicalStrategy: string;
  usesDifferentTypes: string;
  takesCaresOf: string;
  organizesDayRoutines: string;
  usesTools: string;
  respondsBasicNeeds: string;
  takesCriterion: string;
  organizesDayTime: string;
  considerKeyElements: string;
  involvesFamilies: string;
  usesVarietyTools: string;
  recordAndDocument: string;
  plansAccountPrinciple: string;
  characteristicsAgeGroup: string;
  affectiveLearningEnvironment: string;
  offersOportunities: string;
  welcomingAndSafe: string;
  displaysPositiveAttitudes:string;
  positiveLanguageFeedback:string;
  respectfullyAndLovingly:string;
  pedagogicalPractices:string;
  respondsOfNeeds:string;
  promotesAttitudes:string;
  teamworkClassroom:string;
  promotesFreeExpression:string;
  promotesFamilyParticipation:string;
  listenAndRespect:string;
  showReceptiveAttitude:string;
  familiesSomeActivity:string;
  accountFamilyContext:string;
  communicationMechanism:string;
  comprehensiveModel:string;
  setsGoals:string;
  selfEvaluates:string;
  seekContinuousImprovment:string;
  activitiesWorkshop:string;
  agreementOfPlanning:string;
  manageVirtualClassroom:string;
  googleDriveDocs:string;
  technologicalResources:string;
  usesAudiovisualEquipment:string;
}

export type IAttachment7Input = Attachment7Input & AxiosMessage;
